export const ADD_STICKER = 'ADD_STICKER';
export const FETCH_EDITOR_CARD = 'FETCH_EDITOR_CARD';
export const FETCH_EDITOR_CARD_FULFILLED = 'FETCH_EDITOR_CARD_FULFILLED';
export const MOVE_STICKER = 'MOVE_STICKER';
export const SAVE_EDITOR_CARD_TO_SERVER = 'SAVE_EDITOR_CARD_TO_SERVER';
export const UPDATE_CARD_STICKER_ID = 'UPDATE_CARD_STICKER_ID';
export const UPDATE_EDITOR_DATA_SYNC_STATUS = 'UPDATE_EDITOR_DATA_SYNC_STATUS';
